FROM python:3.12-alpine
RUN mkdir -p /var/www

RUN apk update \
  && apk add --no-cache bash vim openssh curl git

WORKDIR /var/www
COPY ./api/requirements.txt ./requirements.txt

RUN pip install --upgrade pip \
  && pip install --upgrade setuptools \
  && pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY api .

EXPOSE 8000

# command to run the app using uvicorn.
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]